### ISSUE TITLE
How is this better than tj/co? 

### ISSUE THREAD

**Issue by gunar** [raksoras/koroutine#1]

**Comment by susheel-aroskar** [comment]
As far as I can tell the latest version of tj/co requires that `yield`ed function returns a Promise. Even older version that was not based on Promises required the `yield`ed call to return a function thunk which means I'd have to write a glue code with a libraries like [mysqljs](https://github.com/mysqljs/mysql) which are purely callback based to use them with tj/co. With koroutine I can directly pass `this.resume` as a callback to any async function that follows node.js's convention of callback(error, result) which I believe results in writing less code.

Also, I wanted some specific functionality like 
- Ability to restrict total run time of a coroutine using the `timeout` parameter 
- Ability to cancel a running coroutine from outside of the coroutine. (`cancel()`)
- Non blocking sleep  (`sleep()`)
- Ability to defer execution of current coroutine till next even loop run (`defer()`)
-  Support for thread local variables (`koroutine.current.context`)

**Comment by gunar** [comment]
Co still accepts yielding thunks. But you're right, I find myself using es6-promifisy to write that "glue code". 

All bullet-points are very reasonable. Thanks for explaining. Maybe this could fit into the README.md. Thanks!

**Comment by raksoras** [comment]
I thought about putting a brief comparison like this with other libraries in README.md but it felt like inviting a flame war :) Besides the reasons mentioned above are my subjective preferences and may not resonate with everyone.

However, thanks for opening this issue. Now I have my reasons documented in a less flame-bait way :) If you don't mind, I'll mark this issue as closed now
